### ISSUE TITLE
Exception catching

### ISSUE THREAD

**Issue by Freegos** [A-BN/fastaUtils#3]
Hello and thank you for your wonderful package.
When the fasta I try to open don't exist (I loop on a lot of folders), my script crash, can you add a catch/try strucure or anything which can avoid this behaviour ?

**Comment by A-BN** [comment]
Well of course, 

this is an excellent suggestion and I think it's the perfect job for my best intern.

**Comment by Freegos** [comment]
Then I'm going to see with him.
